{% set name = "jupyterlab-spreadsheet-editor" %}
{% set version = "0.6.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/jupyterlab-spreadsheet-editor-{{ version }}.tar.gz
  sha256: bffe1d08f1b1b02764d07c9878fd959cf9b15a4680e46fee52a9109009fb5a0c

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.6
    - jupyter_packaging >=0.7.9
    - jupyterlab >=3.0.0rc13,<4.0.0dev0
    - setuptools >=40.8.0
    - wheel
    - pip
  run:
    - python >=3.6
    - jupyterlab >=3.0.0rc13,<4.0.0dev0

test:
  imports:
    # Fails due to dashes, see instead test below.
    # - jupyterlab-spreadsheet-editor
  commands:
    - pip check
    - python -c "from importlib import import_module; import_module('jupyterlab-spreadsheet-editor')"
    - jupyter labextension list
    - jupyter labextension list 1>labextensions 2>&1
    - cat labextensions | grep "spreadsheet-editor.*OK"  # [unix]
  requires:
    - pip

about:
  home: https://github.com/krassowski/jupyterlab-spreadsheet-editor.git
  summary: JupyterLab spreadsheet (csv/tsv) editor
  license: CC0-1.0 AND BSD-3-Clause
  license_file:
    - LICENSE
    - style/icons/LICENSE

extra:
  recipe-maintainers:
    - maresb
    - drhagen
    - krassowski
